targets:
  $default:
    builders:
      secrets_generator:secrets_builder:
        options:
          environment: "" # Default empty points to local .env.secrets, can be overridden by TARGET_ENV env variable
          secrets_dir: "."
          asset_config_paths:
            - "assets/env/.env.dev"
            - "assets/env/.env.staging"
            - "assets/env/.env.prod"
          blocklist:
            - "KEY"
            - "SECRET"
            - "TOKEN"
            - "PASSWORD"
            - "AUTH"
            - "PRIVATE"
          required_keys:
            - "ENCRYPTION_KEY"
            - "BASIC_AUTH_PASSWORD"
            - "APP_AUTH_KEY"
            - "API_SECRET"
          verbose: true
