import 'dart:convert';
import 'dart:io';
import 'package:args/command_runner.dart';
import 'package:crypto/crypto.dart';
import 'package:path/path.dart' as p;
import '../encryptor/aes_gcm_encryptor.dart';
import '../parser/env_parser.dart';
import '../scanner/env_scanner.dart';

/// `envified build --env=<name>` — encrypts discovered files and writes the
/// native payload + `.envified.lock`.
///
/// `--all` processes every discovered environment in one pass.
class BuildCommand extends Command<void> {
  @override
  final String name = 'build';

  @override
  final String description =
      'Encrypt .env.* files and write the native registry + .envified.lock.';

  BuildCommand() {
    argParser
      ..addOption('env', abbr: 'e', help: 'Target environment name.')
      ..addFlag('all', help: 'Build all discovered environments.')
      ..addOption('project-root', abbr: 'r', defaultsTo: '.')
      ..addFlag('inject-platform-files',
          help: 'Also write google-services.json / GoogleService-Info.plist.',
          defaultsTo: false);
  }

  @override
  Future<void> run() async {
    final root = p.absolute(argResults!['project-root'] as String);
    final buildAll = argResults!['all'] as bool;
    final envName = argResults!['env'] as String?;

    if (!buildAll && (envName == null || envName.isEmpty)) {
      stderr.writeln('Error: provide --env=<name> or --all.');
      exitCode = 1;
      return;
    }

    final scanner = EnvScanner(projectRoot: root);
    final scanResult = scanner.scan();

    if (scanResult.isEmpty) {
      stderr.writeln('No .env.* files found. Run envified scan for details.');
      exitCode = 1;
      return;
    }

    final encryptor = AesGcmEncryptor.fromEnvironment(allowPrompt: true);
    final parser = EnvParser();
    final lockEntries = <String, Map<String, String>>{};

    final envsToProcess =
        buildAll ? scanResult.envFiles.keys.toList() : [envName!];

    for (final env in envsToProcess) {
      final file = scanResult.envFiles[env];
      if (file == null) {
        stderr.writeln('Warning: no file found for env "$env" — skipping.');
        continue;
      }

      final content = file.readAsStringSync();
      final values = parser.parse(content);
      final fileHash = sha256.convert(utf8.encode(content)).toString();

      // Encrypt every value and write the generated Dart registry file.
      final encryptedValues = <String, EncryptedPayload>{};
      for (final kv in values.entries) {
        encryptedValues[kv.key] = encryptor.encrypt(kv.value, envName: env);
      }

      _writeGeneratedDart(root, env, encryptedValues);

      lockEntries[env] = {
        'file': file.path,
        'sha256': fileHash,
        'keyCount': '${values.length}',
      };

      stdout.writeln('✓  Built env "$env" (${values.length} keys)');
    }

    _writeLockFile(root, lockEntries);
    stdout.writeln('✓  .envified.lock updated.');
  }

  void _writeGeneratedDart(
    String root,
    String env,
    Map<String, EncryptedPayload> encrypted,
  ) {
    final outDir = Directory(p.join(root, 'lib', 'src', 'generated'));
    outDir.createSync(recursive: true);

    final file = File(p.join(outDir.path, 'envified_registry.$env.g.dart'));
    final buf = StringBuffer()
      ..writeln('// GENERATED BY envified build — DO NOT EDIT BY HAND')
      ..writeln('// ignore_for_file: constant_identifier_names')
      ..writeln()
      ..writeln("// ignore: unused_import")
      ..writeln("import 'dart:convert';")
      ..writeln()
      ..writeln('/// Pre-built AES-256-GCM encrypted registry for env: $env')
      ..writeln('class EnvifiedRegistry\$$env {')
      ..writeln('  EnvifiedRegistry\$$env._();')
      ..writeln()
      ..writeln('  static const String envName = ${jsonEncode(env)};')
      ..writeln()
      ..writeln('  // Encrypted key-value map.')
      ..writeln('  // ciphertext and iv are base64-encoded.')
      ..writeln('  // Decryption happens via the native method channel.')
      ..writeln('  static const Map<String, Map<String, String>> values = {');
    for (final entry in encrypted.entries) {
      buf
        ..writeln('    ${jsonEncode(entry.key)}: {')
        ..writeln("      'ciphertext': ${jsonEncode(entry.value.ciphertext)},")
        ..writeln("      'iv': ${jsonEncode(entry.value.iv)},")
        ..writeln('    },');
    }
    buf
      ..writeln('  };')
      ..writeln('}');

    file.writeAsStringSync(buf.toString());
    stdout.writeln('   → ${file.path}');
  }

  void _writeLockFile(String root, Map<String, Map<String, String>> entries) {
    final file = File(p.join(root, '.envified.lock'));
    final buf = StringBuffer()
      ..writeln('# envified.lock — commit this file.')
      ..writeln('# Generated: ${DateTime.now().toUtc().toIso8601String()}')
      ..writeln('environments:');
    for (final entry in entries.entries) {
      buf
        ..writeln('  ${entry.key}:')
        ..writeln('    file: ${entry.value['file']}')
        ..writeln('    sha256: ${entry.value['sha256']}')
        ..writeln('    keyCount: ${entry.value['keyCount']}');
    }
    file.writeAsStringSync(buf.toString());
  }
}
